var f=Object.defineProperty;var E=Object.getOwnPropertyDescriptor;var O=Object.getOwnPropertyNames;var A=Object.prototype.hasOwnProperty;var P=(o,t)=>{for(var r in t)f(o,r,{get:t[r],enumerable:!0})},R=(o,t,r,e)=>{if(t&&typeof t=="object"||typeof t=="function")for(let s of O(t))!A.call(o,s)&&s!==r&&f(o,s,{get:()=>t[s],enumerable:!(e=E(t,s))||e.enumerable});return o};var S=o=>R(f({},"__esModule",{value:!0}),o);var q={};P(q,{default:()=>g});module.exports=S(q);var p=require("obsidian");var x={"lei complementar":"LC","lei ordin\xE1ria":"LO",lei:"L","decreto-lei":"DL",decreto:"D","medida provis\xF3ria":"MP","emenda constitucional":"EC",resolu\u00E7\u00E3o:"Res",portaria:"Port","instru\xE7\xE3o normativa":"IN"};function M(o){let t=/\*\*\[?(LEI COMPLEMENTAR|LEI ORDINÁRIA|LEI|DECRETO-LEI|DECRETO|MEDIDA PROVISÓRIA|EMENDA CONSTITUCIONAL|RESOLUÇÃO|PORTARIA|INSTRUÇÃO NORMATIVA)\s*[Nn]?[ºª°]?\s*(\d+(?:\.\d+)?),?\s*DE\s*\d+\s*DE\s*\w+\s*DE\s*(\d{4})/i,r=o.match(t);if(!r)return null;let e=V(r[1]),s=r[1].toLowerCase(),i=x[s]||e.substring(0,2).toUpperCase(),a=r[2],n=r[3];return{tipoCompleto:e,tipoAbreviado:i,numero:a,ano:n}}function V(o){return o.toLowerCase().split(" ").map(t=>t.charAt(0).toUpperCase()+t.slice(1)).join(" ")}function N(o){let{tipoCompleto:t,tipoAbreviado:r,numero:e,ano:s}=o;return[`${t} n\xBA ${e}/${s}`,`${r} n\xBA ${e}/${s}`,`${t} ${e}/${s}`,`${r} ${e}/${s}`]}function D(o){let t=/^---\n([\s\S]*?)\n---/,r=o.match(t);if(!r)return o;let e=r[1],s=M(o);if(!s)return o;let a=`aliases:
${N(s).map(n=>`  - "${n}"`).join(`
`)}`;if(/^aliases:/m.test(e)){let n=e.replace(/^aliases:[\s\S]*?(?=\n\w|\n$)/m,a);return o.replace(t,`---
${n}
---`)}else{let n=`${e}
${a}`;return o.replace(t,`---
${n}
---`)}}function v(o){let t=/\|\s*!\[.*?[Bb]ras.*?\]\(.*?\)\s*\|.*\|\n\|\s*---\s*\|\s*---\s*\|\n?/g;return o.replace(t,"")}function w(o=6){let t="abcdefghijklmnopqrstuvwxyz0123456789",r="";for(let e=0;e<o;e++)r+=t.charAt(Math.floor(Math.random()*t.length));return r}function c(o,t=6){let r;do r=w(t);while(o.has(r));return o.add(r),r}function b(o,t){let r={},e=o;return e=e.replace(/<table[\s\S]*?<\/table>/gi,s=>{let a=`<!--PROTECTED_TABLE_${c(t)}-->`;return r[a]=s,a}),e=e.replace(/(?:^\|.+\|$\n?)+/gm,s=>{if(s.includes("<!--PROTECTED_TABLE_")||s.trim().length<5)return s;let a=`<!--PROTECTED_TABLE_${c(t)}-->`;return r[a]=s,a}),{conteudo:e,tabelas:r}}function I(o,t){let r=o;for(let[e,s]of Object.entries(t))r=r.replace(e,s);return r}var X=[{pattern:/^(LIVRO\s+[IVXLCDM\d]+)$/i,nivel:1},{pattern:/^(ANEXO\s+[IVXLCDM\d]+)$/i,nivel:1},{pattern:/^(TÍTULO\s+[IVXLCDM\d]+)$/i,nivel:2},{pattern:/^(CAPÍTULO\s+[IVXLCDM\d]+)$/i,nivel:3},{pattern:/^(Seção\s+[IVXLCDM\d]+)$/i,nivel:4},{pattern:/^(Subseção\s+[IVXLCDM\d]+)$/i,nivel:5}];function L(o){let t=o.split(`
`),r=[],e=0;for(;e<t.length;){let s=t[e],i=s.trim();if(s.trimStart().startsWith(">")){r.push(s),e++;continue}let a=!1;for(let n of X){let h=i.match(n.pattern);if(h){let $=h[1],T="#".repeat(n.nivel),d="",l=e+1;for(;l<t.length&&t[l].trim()==="";)l++;if(l<t.length){let m=t[l].trim();m&&!U(m)&&(d=m,e=l)}d?r.push(`${T} ${$} - ${d}`):r.push(`${T} ${$}`),a=!0;break}}a||r.push(t[e]),e++}return r.join(`
`)}function U(o){return[/^(LIVRO|ANEXO|TÍTULO|CAPÍTULO)\s+[IVXLCDM\d]+$/i,/^(Seção|Subseção)\s+[IVXLCDM\d]+$/i,/^Art\.\s*\d+/i,/^§\s*\d+/i,/^Parágrafo único/i,/^[IVXLCDM]+\s*[-–—]/,/^[a-z]\)\s*/,/^<!--/].some(r=>r.test(o))}function C(o,t){let r=o;return r=r.replace(/^(Art\.\s*\d+[º°]?.*)$/gm,e=>`${e} ^${c(t)}`),r=r.replace(/^((?:§\s*\d+[º°]?|Parágrafo único).*)$/gm,e=>`${e} ^${c(t)}`),r=r.replace(/^([IVXLCDM]+\s*[-–—].*)$/gm,e=>`${e} ^${c(t)}`),r=r.replace(/^([a-z]\)\s*.*)$/gm,e=>`${e} ^${c(t)}`),r}var u=class{constructor(){this.tabelasProtegidas={};this.idsUtilizados=new Set}processar(t){let r=t;return r=this.removerBrasaoDoc(r),r=this.protegerTabelasDoc(r),r=this.processarFrontmatterDoc(r),r=this.converterHierarquiaDoc(r),r=this.adicionarIdsDoc(r),r=this.restaurarTabelasDoc(r),r}protegerTabelasDoc(t){let r=b(t,this.idsUtilizados);return this.tabelasProtegidas=r.tabelas,r.conteudo}restaurarTabelasDoc(t){return I(t,this.tabelasProtegidas)}processarFrontmatterDoc(t){return D(t)}removerBrasaoDoc(t){return v(t)}converterHierarquiaDoc(t){return L(t)}adicionarIdsDoc(t){return C(t,this.idsUtilizados)}};var g=class extends p.Plugin{async onload(){this.processador=new u,this.addCommand({id:"processar-legislacao",name:"Processar documento de legisla\xE7\xE3o",editorCallback:async(t,r)=>{if(!r.file){new p.Notice("Nenhum arquivo aberto");return}try{let s=t.getValue(),i=this.processador.processar(s);t.setValue(i),new p.Notice("Documento processado com sucesso!")}catch(s){console.error("Erro ao processar documento:",s),new p.Notice("Erro ao processar documento. Verifique o console.")}}}),console.log("Plugin Legisla\xE7\xE3o Limpa carregado")}onunload(){console.log("Plugin Legisla\xE7\xE3o Limpa descarregado")}};
