var I=Object.defineProperty;var M=Object.getOwnPropertyDescriptor;var x=Object.getOwnPropertyNames;var X=Object.prototype.hasOwnProperty;var w=(s,r)=>{for(var t in r)I(s,t,{get:r[t],enumerable:!0})},U=(s,r,t,o)=>{if(r&&typeof r=="object"||typeof r=="function")for(let e of x(r))!X.call(s,e)&&e!==t&&I(s,e,{get:()=>r[e],enumerable:!(o=M(r,e))||o.enumerable});return s};var Z=s=>U(I({},"__esModule",{value:!0}),s);var K={};w(K,{default:()=>f});module.exports=Z(K);var u=require("obsidian");var z={"lei complementar":"LC","lei ordin\xE1ria":"LO",lei:"L","decreto-lei":"DL",decreto:"D","medida provis\xF3ria":"MP","emenda constitucional":"EC",resolu\u00E7\u00E3o:"Res",portaria:"Port","instru\xE7\xE3o normativa":"IN"};function j(s){let r=/\*\*\[?(LEI COMPLEMENTAR|LEI ORDINÁRIA|LEI|DECRETO-LEI|DECRETO|MEDIDA PROVISÓRIA|EMENDA CONSTITUCIONAL|RESOLUÇÃO|PORTARIA|INSTRUÇÃO NORMATIVA)\s*[Nn]?[ºª°]?\s*(\d+(?:\.\d+)?),?\s*DE\s*\d+\s*DE\s*\w+\s*DE\s*(\d{4})/i,t=s.match(r);if(!t)return null;let o=q(t[1]),e=t[1].toLowerCase(),n=z[e]||o.substring(0,2).toUpperCase(),i=t[2],c=t[3];return{tipoCompleto:o,tipoAbreviado:n,numero:i,ano:c}}function q(s){return s.toLowerCase().split(" ").map(r=>r.charAt(0).toUpperCase()+r.slice(1)).join(" ")}function _(s){let{tipoCompleto:r,tipoAbreviado:t,numero:o,ano:e}=s;return[`${r} n\xBA ${o}/${e}`,`${t} n\xBA ${o}/${e}`,`${r} ${o}/${e}`,`${t} ${o}/${e}`]}function L(s){let r=/^---\n([\s\S]*?)\n---/,t=s.match(r);if(!t)return s;let o=t[1],e=j(s);if(!e)return s;let i=`aliases:
${_(e).map(c=>`  - "${c}"`).join(`
`)}`;if(/^aliases:/m.test(o)){let c=o.replace(/^aliases:[\s\S]*?(?=\n\w|\n$)/m,i);return s.replace(r,`---
${c}
---`)}else{let c=`${o}
${i}`;return s.replace(r,`---
${c}
---`)}}function T(s){let r=/\|\s*!\[.*?[Bb]ras.*?\]\(.*?\)\s*\|.*\|\n\|\s*---\s*\|\s*---\s*\|\n?/g;return s.replace(r,"")}function y(s=6){let r="abcdefghijklmnopqrstuvwxyz0123456789",t="";for(let o=0;o<s;o++)t+=r.charAt(Math.floor(Math.random()*r.length));return t}function D(s,r=6){let t;do t=y(r);while(s.has(t));return s.add(t),t}function A(s,r){let t={},o=s;return o=o.replace(/<table[\s\S]*?<\/table>/gi,e=>{let i=`<!--PROTECTED_TABLE_${D(r)}-->`;return t[i]=e,i}),o=o.replace(/(?:^\|.+\|$\n?)+/gm,e=>{if(e.includes("<!--PROTECTED_TABLE_")||e.trim().length<5)return e;let i=`<!--PROTECTED_TABLE_${D(r)}-->`;return t[i]=e,i}),{conteudo:o,tabelas:t}}function b(s,r){let t=s;for(let[o,e]of Object.entries(r))t=t.replace(o,e);return t}var F=[{pattern:/^(LIVRO\s+[IVXLCDM\d]+(?:-[A-Z])?)$/i,nivel:1},{pattern:/^(ANEXO\s+[IVXLCDM\d]+(?:-[A-Z])?)$/i,nivel:1},{pattern:/^(TÍTULO\s+[IVXLCDM\d]+(?:-[A-Z])?)$/i,nivel:2},{pattern:/^(CAPÍTULO\s+[IVXLCDM\d]+(?:-[A-Z])?)$/i,nivel:3},{pattern:/^(Seção\s+[IVXLCDM\d]+(?:-[A-Z])?)$/i,nivel:4},{pattern:/^(Subseção\s+[IVXLCDM\d]+(?:-[A-Z])?)$/i,nivel:5}];function E(s){let r=s.split(`
`),t=[],o=0;for(;o<r.length;){let e=r[o],n=e.trim();if(e.trimStart().startsWith(">")){t.push(e),o++;continue}let i=!1;for(let c of F){let a=n.match(c.pattern);if(a){let l=a[1],g="#".repeat(c.nivel),h="",p=o+1;for(;p<r.length;){let v=r[p].trim();if(v===""||B(v)){p++;continue}h=v,o=p;break}h?t.push(`${g} ${l} - ${h}`):t.push(`${g} ${l}`),i=!0;break}}i||t.push(r[o]),o++}return t.join(`
`)}function B(s){return[/^(LIVRO|ANEXO|TÍTULO|CAPÍTULO)\s+[IVXLCDM\d]+(?:-[A-Z])?$/i,/^(Seção|Subseção)\s+[IVXLCDM\d]+(?:-[A-Z])?$/i,/^Art\.\s*\d+/i,/^§\s*\d+/i,/^Parágrafo único/i,/^[IVXLCDM]+\s*[-–—]/,/^[a-z]\)\s*/,/^<!--/,/^\[.+\]$/].some(t=>t.test(s))}var k=[/^Art\.\s/i,/^§\s*\d+/i,/^Parágrafo único/i,/^[IVXLCDM]+\s*[-–—]/,/^[a-z]\)\s/];function O(s){let r=s.trimStart();return k.some(t=>t.test(r))}function C(s){var o;let r=s.split(`
`),t=[];for(let e of r){if(e.trim()===""){t.push(e);continue}if(e.trimStart().startsWith(">")){t.push(e);continue}if(e.trimStart().startsWith("~~")){t.push(e);continue}if((((o=e.match(/^(\s*)/))==null?void 0:o[1])||"").length>=4&&!O(e)){t.push(e);continue}O(e)?t.push(e.trimStart()):t.push(e)}return t.join(`
`)}var m=[/^\*\*(LIVRO\s+[IVXLCDM\d]+(?:-[A-Z])?)\*\*$/i,/^\*\*(ANEXO\s+[IVXLCDM\d]+(?:-[A-Z])?)\*\*$/i,/^\*\*(TÍTULO\s+[IVXLCDM\d]+(?:-[A-Z])?)\*\*$/i,/^\*\*(CAPÍTULO\s+[IVXLCDM\d]+(?:-[A-Z])?)\*\*$/i,/^\*\*(Seção\s+[IVXLCDM\d]+(?:-[A-Z])?)\*\*$/i,/^\*\*(Subseção\s+[IVXLCDM\d]+(?:-[A-Z])?)\*\*$/i];function W(s){let r=s.trim();return m.some(t=>t.test(r))}function G(s){let r=s.trim(),t=r.replace(/^\*\*(.+)\*\*$/,"$1");return!t||[/^Art\.\s/i,/^§\s*\d+/i,/^Parágrafo único/i,/^[IVXLCDM]+\s*[-–—]/,/^[a-z]\)\s/,/^(LIVRO|ANEXO|TÍTULO|CAPÍTULO|Seção|Subseção)\s+[IVXLCDM\d]+(?:-[A-Z])?$/i].some(e=>e.test(t))?!1:/^\*\*[A-ZÀÁÂÃÇÉÊÍÓÔÕÚ]/.test(r)}function R(s){return s.replace(/^\*\*(.+)\*\*$/,"$1")}function S(s){let r=s.split(`
`),t=[];for(let o=0;o<r.length;o++){let e=r[o],n=e.trim();if(W(e)){t.push(R(n));continue}if(G(e)){let i=!1;if(o>0){let c=r[o-1].trim();if((m.some(a=>a.test(`**${c}**`))||m.some(a=>a.test(c)))&&(i=!0),o>1&&c===""){let a=r[o-2].trim();(m.some(l=>l.test(`**${a}**`))||m.some(l=>l.test(a)))&&(i=!0)}}if(i){t.push(R(n));continue}}t.push(e)}return t.join(`
`)}function N(s){return s.trimStart().startsWith("~~")}function H(s,r){for(let t=r;t<s.length;t++)if(s[t].trim()!=="")return s[t];return null}function P(s){let r=s.split(`
`),t=[],o=!1;for(let e=0;e<r.length;e++){let n=r[e],i=N(n),c=n.trim()==="";if(i)o||(t.push("> [!Quote]- Reda\xE7\xE3o revogada"),o=!0),t.push(`> ${n.trimStart()}`);else if(c&&o){let a=H(r,e+1);a&&N(a)?t.push(">"):(o=!1,t.push(""))}else o=!1,t.push(n)}return t.join(`
`)}var d=class{constructor(){this.tabelasProtegidas={};this.idsUtilizados=new Set}processar(r){let t=r;return t=this.removerBrasaoDoc(t),t=this.protegerTabelasDoc(t),t=this.processarFrontmatterDoc(t),t=this.converterNegritoDoc(t),t=this.removerIndentacaoDoc(t),t=this.converterHierarquiaDoc(t),t=this.restaurarTabelasDoc(t),t=this.agruparRevogadasDoc(t),t}protegerTabelasDoc(r){let t=A(r,this.idsUtilizados);return this.tabelasProtegidas=t.tabelas,t.conteudo}restaurarTabelasDoc(r){return b(r,this.tabelasProtegidas)}processarFrontmatterDoc(r){return L(r)}removerBrasaoDoc(r){return T(r)}converterNegritoDoc(r){return S(r)}removerIndentacaoDoc(r){return C(r)}converterHierarquiaDoc(r){return E(r)}agruparRevogadasDoc(r){return P(r)}};var $=/\^([a-z0-9]{6})/g;function Q(s){let r=new Set,t=s.split(`
`);for(let o of t)if(!o.trimStart().startsWith("~~"))for(let e of o.matchAll($))r.add(e[1]);return Array.from(r)}async function Y(s,r,t){let o=new Set;if(t.length===0)return o;let e=s.getMarkdownFiles(),n=t.map(a=>a.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).join("|"),i=new RegExp(`\\[\\[(?:[^\\]]+)?#\\^(${n})(?:\\|[^\\]]*)?\\]\\]`,"g"),c=r.replace(".md","");for(let a of e)if(a.basename!==c){try{let l=await s.cachedRead(a);for(let g of l.matchAll(i))o.add(g[1])}catch(l){console.error(`Erro ao ler arquivo ${a.path}:`,l)}if(o.size===t.length)break}return o}function J(s,r){let t=Array.from(s.matchAll($));if(t.length===0)return s;let o=t.map(n=>n[1]).filter(n=>r.has(n)),e=s.replace($,"").trim();for(let n of o)e=`${e} ^${n}`;return e}async function V(s,r,t){let o=Q(t);if(o.length===0)return{conteudo:t,relatorio:[]};let e=await Y(s,r.name,o),n=o.filter(l=>!e.has(l));if(n.length===0)return{conteudo:t,relatorio:[]};let c=t.split(`
`).map(l=>l.trimStart().startsWith("~~")?l:J(l,e)),a=[];return a.push(`IDs no documento: ${o.length}`),a.push(`IDs com refer\xEAncias (preservados): ${e.size}`),e.size>0&&a.push(`  ${Array.from(e).map(l=>`^${l}`).join(", ")}`),a.push(`IDs sem refer\xEAncias (removidos): ${n.length}`),{conteudo:c.join(`
`),relatorio:a}}var f=class extends u.Plugin{async onload(){this.processador=new d,this.addCommand({id:"processar-legislacao",name:"Processar documento de legisla\xE7\xE3o",editorCallback:async(r,t)=>{let o=t.file;if(!o){new u.Notice("Nenhum arquivo aberto");return}try{let e=r.getValue(),n=this.processador.processar(e),i=await V(this.app.vault,o,n);n=i.conteudo,i.relatorio.length>0&&(console.log("=== Limpeza de IDs ==="),i.relatorio.forEach(c=>console.log(c))),r.setValue(n),new u.Notice("Documento processado com sucesso!")}catch(e){console.error("Erro ao processar documento:",e),new u.Notice("Erro ao processar documento. Verifique o console.")}}}),console.log("Plugin Legisla\xE7\xE3o Limpa carregado")}onunload(){console.log("Plugin Legisla\xE7\xE3o Limpa descarregado")}};
