var S=Object.defineProperty;var q=Object.getOwnPropertyDescriptor;var X=Object.getOwnPropertyNames;var _=Object.prototype.hasOwnProperty;var k=(s,t)=>{for(var r in t)S(s,r,{get:t[r],enumerable:!0})},B=(s,t,r,a)=>{if(t&&typeof t=="object"||typeof t=="function")for(let o of X(t))!_.call(s,o)&&o!==r&&S(s,o,{get:()=>t[o],enumerable:!(a=q(t,o))||a.enumerable});return s};var j=s=>B(S({},"__esModule",{value:!0}),s);var dt={};k(dt,{default:()=>R});module.exports=j(dt);var h=require("obsidian");var y={"lei complementar":"LC","lei ordin\xE1ria":"LO",lei:"L","decreto-lei":"DL",decreto:"D","medida provis\xF3ria":"MP","emenda constitucional":"EC",resolu\u00E7\u00E3o:"Res",portaria:"Port","instru\xE7\xE3o normativa":"IN"};function Z(s){let t=/\*\*\[?(LEI COMPLEMENTAR|LEI ORDINÁRIA|LEI|DECRETO-LEI|DECRETO|MEDIDA PROVISÓRIA|EMENDA CONSTITUCIONAL|RESOLUÇÃO|PORTARIA|INSTRUÇÃO NORMATIVA)\s*[Nn]?[ºª°]?\s*(\d+(?:\.\d+)?),?\s*DE\s*\d+\s*DE\s*\w+\s*DE\s*(\d{4})/i,r=s.match(t);if(!r)return null;let a=H(r[1]),o=r[1].toLowerCase(),n=y[o]||a.substring(0,2).toUpperCase(),e=r[2],i=r[3];return{tipoCompleto:a,tipoAbreviado:n,numero:e,ano:i}}function H(s){return s.toLowerCase().split(" ").map(t=>t.charAt(0).toUpperCase()+t.slice(1)).join(" ")}function G(s){let{tipoCompleto:t,tipoAbreviado:r,numero:a,ano:o}=s;return[`${t} n\xBA ${a}/${o}`,`${r} n\xBA ${a}/${o}`,`${t} ${a}/${o}`,`${r} ${a}/${o}`]}function J(s){let t=[],r=s.match(/^aliases:\s*\n((?:\s+-\s*.+\n?)*)/m);if(r){let o=r[1].split(`
`);for(let n of o){let e=n.match(/^\s+-\s*["']?([^"'\n]+)["']?\s*$/);e&&t.push(e[1].trim())}return t}let a=s.match(/^aliases:\s*\[([^\]]*)\]/m);if(a){let o=a[1].split(",");for(let n of o){let e=n.trim().replace(/^["']|["']$/g,"");e&&t.push(e)}}return t}function W(s){let t=s.split(`
`),r=[],a=!1;for(let o of t){if(/^aliases:/.test(o)){a=!0,/^aliases:\s*\[/.test(o)&&(a=!1);continue}if(a){if(/^\s+-/.test(o)||/^\s+["']/.test(o))continue;a=!1}r.push(o)}return r.join(`
`)}function D(s){let t=/^---\n([\s\S]*?)\n---/,r=s.match(t);if(!r)return s;let a=r[1],o=Z(s);if(!o)return s;let n=G(o),e=J(a),i=new Set(e);for(let p of n)i.add(p);let c=`aliases:
${Array.from(i).map(p=>`  - "${p}"`).join(`
`)}`,l=W(a),u=l.trim()?`${l}
${c}`:c;return s.replace(t,`---
${u}
---`)}function b(s){let t=/\|\s*!\[.*?[Bb]ras.*?\]\(.*?\)\s*\|.*\|\n\|\s*---\s*\|\s*---\s*\|\n?/g;return s.replace(t,"")}function Q(s=6){let t="abcdefghijklmnopqrstuvwxyz0123456789",r="";for(let a=0;a<s;a++)r+=t.charAt(Math.floor(Math.random()*t.length));return r}function T(s,t=6){let r;do r=Q(t);while(s.has(r));return s.add(r),r}function L(s,t){let r={},a=s;return a=a.replace(/<table[\s\S]*?<\/table>/gi,o=>{let e=`<!--PROTECTED_TABLE_${T(t)}-->`;return r[e]=o,e}),a=a.replace(/(?:^\|.+\|$\n?)+/gm,o=>{if(o.includes("<!--PROTECTED_TABLE_")||o.trim().length<5)return o;let e=`<!--PROTECTED_TABLE_${T(t)}-->`;return r[e]=o,e}),{conteudo:a,tabelas:r}}function M(s,t){let r=s;for(let[a,o]of Object.entries(t))r=r.replace(a,o);return r}var Y=[{pattern:/^(LIVRO\s+[IVXLCDM\d]+)$/i,nivel:1},{pattern:/^(ANEXO\s+[IVXLCDM\d]+)$/i,nivel:1},{pattern:/^(TÍTULO\s+[IVXLCDM\d]+)$/i,nivel:2},{pattern:/^(CAPÍTULO\s+[IVXLCDM\d]+)$/i,nivel:3},{pattern:/^(Seção\s+[IVXLCDM\d]+)$/i,nivel:4},{pattern:/^(Subseção\s+[IVXLCDM\d]+)$/i,nivel:5}],K=/^#{1,6}\s+(LIVRO|ANEXO|TÍTULO|CAPÍTULO|Seção|Subseção)\s+[IVXLCDM\d]+(\s*[-–—].*)?$/i;function C(s){let t=s.split(`
`),r=[],a=0;for(;a<t.length;){let o=t[a],n=o.trim();if(K.test(n)){r.push(o),a++;continue}if(o.trimStart().startsWith(">")){r.push(o),a++;continue}let e=!1;for(let i of Y){let g=n.match(i.pattern);if(g){let c=g[1],l="#".repeat(i.nivel),u="",p=a+1;for(;p<t.length&&t[p].trim()==="";)p++;if(p<t.length){let m=t[p].trim();m&&!tt(m)&&(u=m,a=p)}u?r.push(`${l} ${c} - ${u}`):r.push(`${l} ${c}`),e=!0;break}}e||r.push(t[a]),a++}return r.join(`
`)}function tt(s){return[/^(LIVRO|ANEXO|TÍTULO|CAPÍTULO)\s+[IVXLCDM\d]+$/i,/^(Seção|Subseção)\s+[IVXLCDM\d]+$/i,/^Art\.\s*\d+/i,/^§\s*\d+/i,/^Parágrafo único/i,/^[IVXLCDM]+\s*[-–—]/,/^[a-z]\)\s*/,/^<!--/].some(r=>r.test(s))}var rt=/\s\^[a-z0-9]{6}$/,A={artigo:/^\*\*Art\.\s*(\d+[º°]?(?:-[A-Z])?)\*\*/,paragrafo:/^§\s*(\d+[º°]?)/,paragrafoUnico:/^Parágrafo único/i,inciso:/^([IVXLCDM]+)\s*[-–—]/,alinea:/^([a-z])\)/};function E(s,t,r){let a=s.split(`
`),o=[],n=null,e=null,i=null;for(let l of a){let u=l.trim();if(rt.test(u)){o.push(l),g(u);continue}let{tipo:p,chave:m,novaLinha:f}=c(l,u);if(p&&m){let d;r!=null&&r.has(m)?(d=r.get(m),t.add(d)):d=T(t),o.push(`${f} ^${d}`)}else o.push(l)}return o.join(`
`);function g(l){let u=l.match(A.artigo);if(u){n=`Art. ${u[1]}`,e=null,i=null;return}if(A.paragrafoUnico.test(l)){e="Par\xE1grafo \xFAnico",i=null;return}let p=l.match(A.paragrafo);if(p){e=`\xA7 ${p[1]}`,i=null;return}let m=l.match(A.inciso);if(m){i=m[1];return}}function c(l,u){let p=u.match(A.artigo);if(p)return n=`Art. ${p[1]}`,e=null,i=null,{tipo:"artigo",chave:n,novaLinha:l};if(A.paragrafoUnico.test(u))return e="Par\xE1grafo \xFAnico",i=null,{tipo:"paragrafoUnico",chave:n?`Par\xE1grafo \xFAnico do ${n}`:null,novaLinha:l};let m=u.match(A.paragrafo);if(m){let $=`\xA7 ${m[1]}`;return e=$,i=null,{tipo:"paragrafo",chave:n?`${$} do ${n}`:null,novaLinha:l}}let f=u.match(A.inciso);if(f){let $=f[1];i=$;let v=n;return e&&n&&(v=`${e} do ${n}`),{tipo:"inciso",chave:v?`${$} do ${v}`:null,novaLinha:l}}let d=u.match(A.alinea);if(d){let $=d[1],v=n;return i?e&&n?v=`${i} do ${e} do ${n}`:n&&(v=`${i} do ${n}`):e&&n&&(v=`${e} do ${n}`),{tipo:"alinea",chave:v?`${$}) do ${v}`:null,novaLinha:l}}return{tipo:null,chave:null,novaLinha:l}}}var ot=/^(\s*)(\*\*)?(Art\.\s*\d+[º°]?(?:-[A-Z])?)(\*\*)?\s*(.*)$/gm;function P(s){return s.replace(ot,(t,r,a,o,n,e)=>{let i=o.trim(),g=e.trim();return g?`**${i}** ${g}`:`**${i}**`})}function at(s){let t=s.replace(/Art\*\*\.\*\*\s*/g,"Art. ");return t=t.replace(/^(Art\.\s*\d+)\*\*\.\*\*([A-ZÀ-Ú])/gm,"$1. $2"),t}function st(s){return s.replace(/^(Art\.\s*\d+[º°](?:-[A-Z])?)([A-ZÀ-Ú])/gm,"$1 $2")}function nt(s){return s.replace(/^(§\s*\d+[º°])([A-ZÀ-Ú])/gm,"$1 $2")}function et(s){return s.replace(/  +/g," ")}function x(s){let t=s;return t=at(t),t=st(t),t=nt(t),t=et(t),t}var it={artigo:/^(?:\*\*)?Art\.\s*(\d+[º°]?(?:-[A-Z])?)/i,paragrafo:/^§\s*(\d+[º°]?)/i,paragrafoUnico:/^Parágrafo único/i,inciso:/^([IVXLCDM]+)\s*[-–—]/,alinea:/^([a-z])\)/,item:/^(\d+)\\\./};function w(s){let t=s.trim();for(let[r,a]of Object.entries(it)){let o=t.match(a);if(o)return r==="paragrafoUnico"?"Par\xE1grafo \xFAnico":`${r}:${o[1]}`}return null}function ct(s){return/\[\(Redação dada pela/.test(s)}function O(s){let t=s.split(`
`),r=[],a=0;for(;a<t.length;){let o=t[a],n=w(o);if(!n){r.push(o),a++;continue}let e=a+1;for(;e<t.length&&t[e].trim()==="";)e++;if(e<t.length){let i=t[e];if(w(i)===n&&ct(i)){r.push("> [!note]- Reda\xE7\xE3o original"),r.push(`> ${o.trim()}`),r.push(""),a=e;continue}}r.push(o),a++}return r.join(`
`)}var z=class{constructor(){this.tabelasProtegidas={};this.idsUtilizados=new Set}processar(t){let r=t;return r=this.normalizarTextoClipadoDoc(r),r=this.processarDuplicatasDoc(r),r=this.removerBrasaoDoc(r),r=this.protegerTabelasDoc(r),r=this.processarFrontmatterDoc(r),r=this.converterHierarquiaDoc(r),r=this.normalizarArtigosDoc(r),r=this.adicionarIdsDoc(r),r=this.restaurarTabelasDoc(r),r}protegerTabelasDoc(t){let r=L(t,this.idsUtilizados);return this.tabelasProtegidas=r.tabelas,r.conteudo}restaurarTabelasDoc(t){return M(t,this.tabelasProtegidas)}processarFrontmatterDoc(t){return D(t)}removerBrasaoDoc(t){return b(t)}converterHierarquiaDoc(t){return C(t)}normalizarArtigosDoc(t){return P(t)}adicionarIdsDoc(t){return E(t,this.idsUtilizados)}normalizarTextoClipadoDoc(t){return x(t)}processarDuplicatasDoc(t){return O(t)}};var lt=/\^([a-z0-9]{6})/g,I={artigo:/^\*\*Art\.\s*(\d+[º°]?(?:-[A-Z])?)\*\*/,paragrafo:/^§\s*(\d+[º°]?)/,paragrafoUnico:/^Parágrafo único/i,inciso:/^([IVXLCDM]+)\s*[-–—]/,alinea:/^([a-z])\)/};function V(s){let t=new Map,r=s.split(`
`),a=null,o=null,n=null;for(let e of r){let i=e.trim();if(!i)continue;let g=[...i.matchAll(lt)],c=g.length>0?g[0][1]:null,l=i.match(I.artigo);if(l){a=`Art. ${l[1]}`,o=null,n=null,c&&t.set(a,c);continue}if(I.paragrafoUnico.test(i)){if(o="Par\xE1grafo \xFAnico",n=null,c&&a){let f=`Par\xE1grafo \xFAnico do ${a}`;t.set(f,c)}continue}let u=i.match(I.paragrafo);if(u){let f=`\xA7 ${u[1]}`;if(o=f,n=null,c&&a){let d=`${f} do ${a}`;t.set(d,c)}continue}let p=i.match(I.inciso);if(p){let f=p[1];if(n=f,c){let d=a;if(o&&a&&(d=`${o} do ${a}`),d){let $=`${f} do ${d}`;t.set($,c)}}continue}let m=i.match(I.alinea);if(m){let f=m[1];if(c){let d=a;if(n?o&&a?d=`${n} do ${o} do ${a}`:a&&(d=`${n} do ${a}`):o&&a&&(d=`${o} do ${a}`),d){let $=`${f}) do ${d}`;t.set($,c)}}continue}}return t}function U(s,t){let r=V(s),a=r.size,o=t,n={},e=new Set;o=x(o);let i=o;o=O(o);let g=(i.match(/\(Redação dada pela/g)||[]).length;o=b(o);let c=L(o,e);o=c.conteudo,Object.assign(n,c.tabelas),o=ut(s,o),o=C(o),o=P(o),o=E(o,e,r),o=M(o,n);let l=gt(o,r),u=e.size-l;return{conteudo:o,idsReutilizados:l,idsNovos:u,duplicatasProcessadas:g}}function ut(s,t){let r=/^---\n([\s\S]*?)\n---/,a=s.match(r),o=t.match(r);if(!a||!o)return D(t);let n=pt(a[1]),e=D(t);if(n.length>0){let i=e.match(r);if(i){let g=i[1];g=g.replace(/(aliases:\n(?:\s+-\s*"[^"]+"\n)*)/,c=>{let l=n.filter(p=>!c.includes(p)).map(p=>`  - "${p}"`).join(`
`),u=c.endsWith(`
`)?c:c+`
`;return l?`${u}${l}
`:c}),e=e.replace(r,`---
${g}
---`)}}return e}function pt(s){let t=[],r=s.split(`
`),a=!1,o=[/^(Lei Complementar|LC|Lei|L|Decreto|D|Medida Provisória|MP|Emenda Constitucional|EC)\s*(nº\s*)?\d+/i];for(let n of r){if(/^aliases:/.test(n)){a=!0;continue}if(a)if(/^\s+-/.test(n)){let e=n.match(/^\s+-\s*["']?([^"'\n]+)["']?/);if(e){let i=e[1].trim();o.some(c=>c.test(i))||t.push(i)}}else/^\s/.test(n)||(a=!1)}return t}function gt(s,t){let r=0;for(let a of t.values())s.includes(`^${a}`)&&r++;return r}var N=class extends h.FuzzySuggestModal{constructor(t,r,a){super(t),this.arquivos=r,this.onEscolha=a,this.setPlaceholder("Selecione o arquivo de legisla\xE7\xE3o existente para atualizar")}getItems(){return this.arquivos}getItemText(t){return t.basename}onChooseItem(t){this.onEscolha(t)}},R=class extends h.Plugin{async criarBackup(t){var i;let r=new Date().toISOString().replace(/T/," ").replace(/\..+/,"").replace(/:/g,""),a=`${t.basename} - backup ${r}.md`,o=((i=t.parent)==null?void 0:i.path)||"",n=o?`${o}/${a}`:a;return await this.app.vault.copy(t,n)}async onload(){this.processador=new z,this.addCommand({id:"processar-legislacao",name:"Processar documento de legisla\xE7\xE3o",editorCallback:async(t,r)=>{if(!r.file){new h.Notice("Nenhum arquivo aberto");return}try{let o=t.getValue(),n=this.processador.processar(o);t.setValue(n),new h.Notice("Documento processado com sucesso!")}catch(o){console.error("Erro ao processar documento:",o),new h.Notice("Erro ao processar documento. Verifique o console.")}}}),this.addCommand({id:"atualizar-legislacao",name:"Atualizar legisla\xE7\xE3o com nova vers\xE3o",editorCallback:async(t,r)=>{let a=r.file;if(!a){new h.Notice("Nenhum arquivo aberto");return}let o=this.app.vault.getMarkdownFiles().filter(n=>n.path!==a.path).sort((n,e)=>n.basename.localeCompare(e.basename));if(o.length===0){new h.Notice("Nenhum outro arquivo encontrado no vault");return}new N(this.app,o,async n=>{try{let e=t.getValue(),i=await this.app.vault.read(n),g=await this.criarBackup(n),c=U(i,e);await this.app.vault.modify(n,c.conteudo),new h.Notice(`Legisla\xE7\xE3o atualizada!
Backup criado: ${g.basename}
IDs reutilizados: ${c.idsReutilizados}
IDs novos: ${c.idsNovos}
Duplicatas: ${c.duplicatasProcessadas}`),new h.Notice(`Arquivo atualizado: ${n.basename}`,5e3)}catch(e){console.error("Erro ao atualizar legisla\xE7\xE3o:",e),new h.Notice("Erro ao atualizar. Verifique o console.")}}).open()}}),console.log("Plugin Legisla\xE7\xE3o Limpa carregado")}onunload(){console.log("Plugin Legisla\xE7\xE3o Limpa descarregado")}};
